catalog_name: maven
schema_name: default

parameters:
  learning_rate: 0.05
  random_state: 42

num_features:
  - name: LIMIT_BAL
    dtype: float64
  - name: SEX
    dtype: int64
  - name: EDUCATION
    dtype: int64
  - name: MARRIAGE
    dtype: int64
  - name: AGE
    dtype: int64
  - name: PAY_0
    dtype: int64
  - name: PAY_2
    dtype: int64
  - name: PAY_3
    dtype: int64
  - name: PAY_4
    dtype: int64
  - name: PAY_5
    dtype: int64
  - name: PAY_6
    dtype: int64
  - name: BILL_AMT1
    dtype: float64
  - name: BILL_AMT2
    dtype: float64
  - name: BILL_AMT3
    dtype: float64
  - name: BILL_AMT4
    dtype: float64
  - name: BILL_AMT5
    dtype: float64
  - name: BILL_AMT6
    dtype: float64
  - name: PAY_AMT1
    dtype: float64
  - name: PAY_AMT2
    dtype: float64
  - name: PAY_AMT3
    dtype: float64
  - name: PAY_AMT4
    dtype: float64
  - name: PAY_AMT5
    dtype: float64
  - name: PAY_AMT6
    dtype: float64


target:
  - name: default.payment.next.month
    dtype: int64

columns_to_drop:
  - ID
