# catalog_name: maven
# schema_name: default

catalog_name: mlops_students
schema_name: benitomartin

parameters:
  learning_rate: 0.05
  random_state: 42
  force_col_wise: true

ab_test:
  learning_rate_a: 0.05
  learning_rate_b: 0.1
  force_col_wise: true
  
num_features:
  - name: ID
    dtype: int64
  - name: LIMIT_BAL
    dtype: float64
  - name: SEX
    dtype: int64
  - name: EDUCATION
    dtype: int64
  - name: MARRIAGE
    dtype: int64
  - name: AGE
    dtype: int64
  - name: PAY_0
    dtype: int64
  - name: PAY_2
    dtype: int64
  - name: PAY_3
    dtype: int64
  - name: PAY_4
    dtype: int64
  - name: PAY_5
    dtype: int64
  - name: PAY_6
    dtype: int64
  - name: BILL_AMT1
    dtype: float64
  - name: BILL_AMT2
    dtype: float64
  - name: BILL_AMT3
    dtype: float64
  - name: BILL_AMT4
    dtype: float64
  - name: BILL_AMT5
    dtype: float64
  - name: BILL_AMT6
    dtype: float64
  - name: PAY_AMT1
    dtype: float64
  - name: PAY_AMT2
    dtype: float64
  - name: PAY_AMT3
    dtype: float64
  - name: PAY_AMT4
    dtype: float64
  - name: PAY_AMT5
    dtype: float64
  - name: PAY_AMT6
    dtype: float64


target:
  - name: default.payment.next.month
    dtype: int64
    new_name: Default

# Scaling Features
features:
  robust:
    - Limit_bal
    - Bill_amt1
    - Bill_amt2
    - Bill_amt3
    - Bill_amt4
    - Bill_amt5
    - Bill_amt6
    - Pay_amt1
    - Pay_amt2
    - Pay_amt3
    - Pay_amt4
    - Pay_amt5
    - Pay_amt6
