name: CI

on:
  push:
    branches:
      - setup  # Trigger on push to the 'setup' branch

  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      # Set up Python 3.11 with uv
      - name: Set up Python 3.11 environment
        run: uv python install 3.11.0

      # Create and activate the virtual environment using uv
      - name: Create virtual environment
        run: |
          uv venv -p 3.11.0 .venv
          source .venv/bin/activate

      # Install dependencies using pyproject.toml
      - name: Install dependencies
        run: uv pip install -r pyproject.toml --all-extras

      # Lock dependencies
      - name: Lock dependencies
        run: uv lock

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files
