name: CI

on:
  push:
    branches:
      - setup  # Trigger on push to the 'setup' branch

  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use GitHub's setup-python action to install Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0

      # Create a virtual environment and install dependencies
      - name: Create virtual environment and install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r pyproject.toml --all-extras
          uv lock

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files
