name: CI

on:
  push:
    branches:
      - setup  # Trigger on push to the 'setup' branch

  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"  # Automatically installs the correct Python version
                                                 # Specified in requires-python
      - name: Create virtual environment
        run: |
          uv venv -p 3.11 .venv

      - name: Activate virtual environment and install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r pyproject.toml --all-extras

      - name: Run pre-commit checks
        run: |
          source .venv/bin/activate
          pre-commit install
          pre-commit run --all-files
